### ISSUE TITLE
如果无法引导，请尝试注入内存信息

### ISSUE THREAD

**Issue by shiweifu** [darkhandz/XPS15-9550-Sierra#1]
引导报了个 CPU 啥啥错误，失败。

然后 Clover 在 SMBIOS 中注入了内存，成功

参考：
http://bbs.pcbeta.com/viewthread-1680865-1-1.html
http://bbs.pcbeta.com/viewthread-1690183-1-1.html

**Comment by darkhandz** [comment]
这个……不知道是不是因为我乱改了一个SMBIOS的机型SerialNumber导致的……我给改回来一个合法的试试，目前你安装情况如何呢

**Comment by shiweifu** [comment]
@darkhandz 
还是不行，我注入个内存信息，安装成了。

状态很不错，蓝牙、无线5g 、睡眠、外放耳机切换都工作的很好。

目前发现的一点个问题是耳机破音

**Comment by darkhandz** [comment]
我还发现即使有了CodecCommander驱动，但是睡眠起来有时候还是无声……
我平时不怎么用耳机，所以没测试到，声卡节点这些要修复的话估计也比较麻烦。
你安装是完全采用我这个Clover的内容吗？没有再手动放置DSDT.aml吧？想看看这方面有没有通用性

**Comment by shiweifu** [comment]
@darkhandz 
没有再弄，就是直接拷过去就工作的很好，我的配置几乎和你一样

另外，显示器在亮度特别低的情况会闪，这个之前讨论过，好像是应该打 brightness 啥的一个补丁

**Comment by darkhandz** [comment]
我这个已经打过亮度补丁了的，可以看ACPI/patched里面的SSDT-PNLF.aml。
亮度的问题我想可能真的是和BIOS有关，可能Dell官方没定出这么低的亮度，我看我在Win10的时候，可调到的最低亮度大概是OSX的第4格的样子，而第4格是不怎么会闪的。
不过奇怪的是，手动去调亮度进度条的话，有些很低的亮度档位也是不会闪的，所以我当时想，能不能自己修改PNLF的档位亮度值，结果发现改了也不生效……可能修改不当，不太会看那些ACPI语言的代码。
