### ISSUE TITLE
装好黑苹果之后怎么装win10？ 

### ISSUE THREAD

**Issue by jianghaizhi** [darkhandz/XPS15-9550-Sierra#101]
按照教程装的UEFI + clover + 10.12.5 + nvme
我试了用磁盘工具在硬盘上分出了一部分空间给win
但是在安装的时候提示说：这块硬盘不能安装win10，因为含有MBR分区索引，win10只能只能安装在UEFI
要怎么搞呢？求助

**Comment by darkhandz** [comment]
可以参照 http://bbs.pcbeta.com/viewthread-1649991-1-1.html 的第三点。
我个人是把win安装在第二个SATA SSD，所以并不能提供单盘双系统的经验了，请自行摸索。

**Comment by jianghaizhi** [comment]
谢谢黑手大哥回复，我刚才试了一下格式化成 苹果格式 然后用win的安装程序重新格式化就行了。

**Comment by darkhandz** [comment]
好的，祝顺利。
