### ISSUE TITLE
已解决--关于HDMI无输出的解决办法！

### ISSUE THREAD

**Issue by qshuai** [darkhandz/XPS15-9550-Sierra#104]
1 使用clover configurator打开clover文件夹中的config.plist文件，在左侧导航栏点击SMBIOS，在右侧找到Board-ID，并记下；

2 打开Finder，使用shift+cmd+g快捷键，进入/System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDevicePolicy.kext/Contents/文件夹，使用文本工具打开info.plist文件；

3 找到ConfigMap关键字，添加以下内容(第三行到第六行)
```
<key>ConfigMap</key>
	<dict>
		<key>Mac-A5C67F76ED83108C(这里换成您的Board-ID)</key>
		<string>none</string>
		<string>Config2</string>
		<key>none</key>
                ...
```

4 重建缓存；

5 重启，慢慢享用吧！

**Comment by Sherlockouo** [comment]
没有权限打开，info.plist 怎么办

**Comment by qshuai** [comment]
sudo vim 。。。
