### ISSUE TITLE
悲剧了，使用最后的Clover,10.12.4系统，主板烧了

### ISSUE THREAD

**Issue by qshuai** [darkhandz/XPS15-9550-Sierra#107]
事情是这样的，我在命令行通过make install安装redis软件，提示我需要make test一下，然后我就敲了sudo make test,感觉会得一会，就去了洗手间，等回来的时候，电脑电源灯灭了，我还以为休眠了，来回安了很多次，长安短按都没用。
另外，插上电源线，充电显示灯不亮。电池电量显示不亮。屏幕更没亮过。
打开后壳，发现gpu靠上的位置有一处损坏，外面有呈现黑色，面积不大，大约1平方厘米，同时后盖上也有黑色痕迹。
dell售后初步给出结论是电压不稳，目前还在维修店里面。如果换主板的话，3000左右。至于保修，店里的人说如果主板表面有明显损坏的，一般不给保修，悲剧了。

**Comment by VAllens** [comment]
厉害了我的哥！！！
黑苹果黑成这样子，也是没谁了。

**Comment by darkhandz** [comment]
很抱歉，发生了这样的事，我也没预料到，也没听说过类似案例……
你可以把相关的软件安装、编译命令发出来我试试。

**Comment by Demogorgon314** [comment]
好像黑苹果cpu过热时 不会像windows一样降频

**Comment by qshuai** [comment]
@darkhandz 维修店里面检测这块主板是一块维修过的主板，好多螺丝有拧过的痕迹，而且有些地方缺失螺丝；
电脑是淘宝上买的，7999元，9550顶配；
所以个人觉得主板烧了和安装软件无关，应该是主板的体质问题；目前正要和淘宝店家协商，但是机器铭牌下面的撕毁不保的标签已经被我撕了（其实我感觉店家就是不想让买家看到主板的真实情况才贴的），大家有什么好建议给我呀！！！

**Comment by darkhandz** [comment]
@scrapup 说是售后检测拆机的时候撕掉的？不知道什么情况……等其他同学支招

**Comment by skinnyshy** [comment]
不知道你换了吗，前段时间我的独显坏掉了，显示花屏，找深水宝置换了，具体是没有动过CPU和显卡的主板加850左右可以置换一个良品。
