### ISSUE TITLE
关于风扇的问题

### ISSUE THREAD

**Issue by Demogorgon314** [darkhandz/XPS15-9550-Sierra#108]
开机后过一会就会发现风扇特别吵，但cpu温度只有30多度，请问有什么好的解决方案吗？@darkhandz

**Comment by darkhandz** [comment]
并没有遇到……一般是跑了CPU占用率高的app才会让风扇特别吵……你可以留意下活动监视器里面的CPU占用。

**Comment by Demogorgon314** [comment]
还有 一个问题 就是亮度没法保存，每次重启就回到最高亮度，这个怎么解决呢？我试了RC script 发现生成了nvram.plist 但是亮度还是没法保存 @darkhandz

**Comment by Demogorgon314** [comment]
刚刚测试了一下 ... 风扇不会像windows一样停转，一旦转速加快就不会变慢了，cpu最低频率@darkhandz 为1.2Ghz @wmchris的最低频率为800Mhz CPU压力测试不会因为过热而降频（不知道是好还是坏）... 为了解决最新BIOS无法启动问题 clover里的drivers64UEFI 用的是 @wmchris 的，改了clover配置加了一句slide=168，

**Comment by darkhandz** [comment]
亮度需要EmuVariableUefi-64.efi和RcScript配合。
800mhz和SMBIOS有关，也可以通过[脚本修改](https://github.com/Piker-Alpha/freqVectorsEdit.sh)得到。
AptioFi只影响内核释放位置，不影响频率和风扇。

**Comment by Demogorgon314** [comment]
EmuVariableUefi-64.efi 和RC Script 都有 但是不知道为什么会保存不了

**Comment by Demogorgon314** [comment]
SMBIOS我把wmchris的改成和你的一样了

**Comment by soulomoon** [comment]
@Demogorgon314 
参照[Laptop backlight control using AppleBacklightInjector.kext](https://www.tonymacx86.com/threads/guide-laptop-backlight-control-using-applebacklightinjector-kext.218222/)的**Saving and restoring backlight level across restarts**一节

NVRAM保存的亮度不生效，原因在每次重启clover会注入一个默认值到NVRAM中，如果要禁止这种行为，需要设置config.plist/SystemParameters/BacklightLevel=0。这样就可以保存亮度了

**Comment by Demogorgon314** [comment]
@soulomoon  非常感谢 现在已经可以保存亮度了。
还有，请问你的风扇可以停转吗。

**Comment by soulomoon** [comment]
@Demogorgon314 
30多度但是风扇还在转，比使用windows要安静多了

**Comment by Demogorgon314** [comment]
@soulomoon macos下基本是稳定2400rpm，windows有时可以停转
