### ISSUE TITLE
键盘capslock问题，快速连按可能导致亮灯的时候仍是小写

### ISSUE THREAD

**Issue by soulomoon** [darkhandz/XPS15-9550-Sierra#112]
键盘capslock问题，快速连按可能导致亮灯的时候仍是小写，再按一次熄灯大写，
键盘的caps灯与电脑不同步，大家有这种情况吗？

**Comment by darkhandz** [comment]
自行下载最新的 [VoodooPSController](https://bitbucket.org/RehabMan/os-x-voodoo-ps2-controller/downloads/) ，我repo这个当时是为了自己使用CapsLock映射到Ctrl这个特性，所以才保留tluck版本的，你可以用回Rehabman的试试。

**Comment by VAllens** [comment]
nice

**Comment by soulomoon** [comment]
@darkhandz  可以了 感谢🙏黑大
