### ISSUE TITLE
希望得到大大的更多帮助

### ISSUE THREAD

**Issue by kandra777** [darkhandz/XPS15-9550-Sierra#12]
根据黑手的教程成功的用上了10.11.6…
我是i5 4K触屏 nvme的9550
但是内建网卡这步不知道怎么具体操作，直接把那段文字粘贴右下的应用又是灰色不可点
求大大为了我这种小白再写详细点！感激不尽

**Comment by darkhandz** [comment]
pcbeta的帖子是有问题的，我没有权限再修正帖子的内容了，所以你还是看我github的完整版教程吧，假网卡的代码修正过了的。

**Comment by kandra777** [comment]
感谢黑手这么快就回复了我的问题。github完整版教程我看了啊 但是内建网卡这块没看懂 能不能加个QQ我截图给你看 你简单指导一下就行。
另外好像有个bug，就是休眠后再开机有时候usb不工作。。再休眠再开机又好了
不知道如何修复，期待你的回复

**Comment by darkhandz** [comment]
你可以用[这个文件](https://github.com/darkhandz/XPS15-9550-Sierra/blob/master/DSDT-HotPatches/Patches/SSDT-RMNE.dsl)生成AML，然后放去ACPI/Patched里，以代替手动打网卡补丁，但是要注意如果你的config.plist指定了AML加载列表的话，也要把这个AML加入到列表里面。
USB唤醒后不工作的话，留意下SSDT-UIAC.aml有没有加载，也要配合USBInjectAll.kext，缺一不可。

**Comment by kandra777** [comment]
好的 真没想到黑手大神这么平易近人 
我现在马上去试试
如果不行的话 我想加你一下qq我截图给你看
我对这个很感兴趣 也希望你能成为我的朋友和老师
我的qq是49256440 
再次真诚的感谢你 黑手大神

**Comment by kandra777** [comment]
你好 黑手！
按照这个方法好了，感谢。说了你别不信，小白的我其实之前试过这样做 但是居然没有在文件名后加。aml的后缀！！！！哈哈 见笑了
不过新问题又来了，内建成功后app store还是无法登陆下载我再继续学习研究
再次感谢

**Comment by darkhandz** [comment]
内建成功后记得再按教程说的，删除掉所有网络配置，然后删除一个plist文件，重启，再按顺序添加 以太网，无线网，然后就可以App Store下载了。

**Comment by kandra777** [comment]
查看了eth0的设备 发现是指派给wifi了
按你的步骤重新安装驱动后 ，删掉了plist文件重启后 果然好了
现在可以访问app store了 很感动 感谢你
我是一名ios软件开发者 对这些底层的东西了解的太少 以后会往这方面学习
希望以后还能得到你的指导，另外能推荐点书籍或者相关的学习资料吗？

**Comment by darkhandz** [comment]
额，我也是照葫芦画瓢的而已……
对了，装好系统后，最好还是把/S/L/E/IONVMeFamily.kext删除掉

**Comment by kandra777** [comment]
别谦虚啊黑手
我删除了nvme的驱动 还需要打你12.1教程里面的补丁吗
其他有需要删的驱动没有？
然后我反馈一个bug，就是外放效果完美 比原来的win10效果好多了
但是插耳机就有很明显的电流声 不知道是我的原因还是驱动的原因

**Comment by darkhandz** [comment]
10.12.1的nvme处理是另外的，你用10.11.6可以不用做其他处理了。
10.12.1也差不多的，不过目前触摸板的驱动还不成熟，所以没啥特别就不强求新版了。
电流声问题要安装CodecCommander.kext和SSDT-ALC298.aml试试，在写10.11.6教程的时候我基本不用耳机，所以没怎么在意这个问题
