### ISSUE TITLE
求告知如何手动清理config.plist里指定驱动的操作方法

### ISSUE THREAD

**Issue by kandra777** [darkhandz/XPS15-9550-Sierra#13]
教程原文：“补丁打完了，现在要把EFI分区里Clover的config.plist里面的所有关于IONVMeFamily的补丁删除”
我打开plist 没有找到关键字IONVMeFamily，具体要怎么清楚啊？
麻烦黑手大大了

**Comment by darkhandz** [comment]
这个是10.12.1的教程，配置和10.11.6有不同的，不可混为一谈呢

**Comment by kandra777** [comment]
我准备升级成12.1，现在已经把11.6的驱动打上补丁了并把原声nvme驱动备份了
但是不知道怎么在plist里面删除ionvmefamily的相关操作
在线等你回复

**Comment by darkhandz** [comment]
10.11.6的Clover的config.plist里我没有放NVMe相关的Patches，所以不需要删除。
如果你想直升10.12.1，你可以试试按《题外-驱动共存》这一节的内容操作，但是我不知道10.11.6的破解驱动是否适用于10.12.1，我也没实测过。
10.12.1的无线网卡补丁和10.11.6也有不同，你需要自己看看我这个repo里面的config.plist的KextPatches里面的项目，有关于WIFI的10.12.x的。
纯黑苹果新手的话，建议先看看Clover的各项设置的作用，才会了解每一步操作是什么意义。
