### ISSUE TITLE
除硬盘（pm951）不同，其余配置相同，完全教程安装反馈

### ISSUE THREAD

**Issue by Supertramplee** [darkhandz/XPS15-9550-Sierra#15]
您好！现在我照着您的教程安装完成，驱动用的您提供的热补丁，现在有如下问题：

1.hdmi输出无效
2.无法识别声卡设备。

现在暂时发现这些问题。不知道是不是我哪里做的不对么？wx 15542517380，方便的话可否加我一下？不胜感激！

**Comment by darkhandz** [comment]
HDMI输出还需要做额外的步骤，[见这里的第九-HDMI输出](https://github.com/darkhandz/XPS15-9550-OSX)
声卡设备，可能需要再清除缓存然后重启多两次看看，因为之前有人遇到同样的问题

**Comment by Supertramplee** [comment]
还有一个问题，多指手势识别不正常。

**Comment by Supertramplee** [comment]
回复好快。。谢谢。，我去试试

**Comment by Supertramplee** [comment]
您可以完善下步骤，比如刚才到hdmi等哪些步骤需要重做，增加到这篇文章里～我两篇都在看，会有遗漏～一点建议。

**Comment by darkhandz** [comment]
额，其实我个人没有HDMI设备，没有USB3.1设备……很多都无法测试，也就干脆不写了，怕误人子弟

**Comment by darkhandz** [comment]
多指手势是因为触摸板驱动不完善，这个没有办法，估计是10.12大改了这部分，导致第三方驱动的作者要花大量时间去适配。
我个人主要是鼠标……所以没什么大影响……

**Comment by Supertramplee** [comment]
重建缓存 显卡部分疯狂报错。。是不是坏掉了。。。

**Comment by darkhandz** [comment]
难道你是4K？报错提示什么？不要只留最后一句错误提示，起码要半屏信息

**Comment by Supertramplee** [comment]
/System/Library/Extensions/AppleGraphicsControl.kext/Contents/PlugIns/AppleGraphicsDeviceControl.kext is not authentic; omitting from prelinked kernel.
Can't use AppleGraphicsDeviceControl.kext - not linked.
Prelink failed for com.apple.driver.AppleIntelSKLGraphicsFramebuffer; omitting from prelinked kernel.
Can't use AppleGraphicsDeviceControl.kext - not linked.
Prelink failed for com.apple.driver.AGPM; omitting from prelinked kernel.
KernelCache ID: 32F00A64E49599FB1CCCEF3D6A0866A8
symlink("/System/Library/PrelinkedKernels/prelinkedkernel", "/System/Library/Caches/com.apple.kext.caches/Startup/kernelcache") failed 17 (File exists) <createPrelinkedKernel 2795>



我的是1080，上面是重启以后又尝试重制的信息，显卡驱动已然挂了，看来我得重装了。。。

**Comment by darkhandz** [comment]
额，编辑文件之前都应该复制一份……你这个情况可以试试Clover按空格键，选择Safe-mode，看看能不能进系统。
先搞好其他，最后再搞HDMI吧

**Comment by Supertramplee** [comment]
我再重做一次吧。现在虽然挂了但是还能进系统，五国报错但是能进来。
完全用你的文件做好u盘，然后装好系统，更改引导，直接用u盘的Clover文件夹替换系统efi的Clover，（之前部分替换进不了系统，5国报错，用的最新的3949clover），然后改语言重启，安装其他驱动，nvme补丁，重建网卡。
之前版本的教程里面，六／七两步没有做，是不是应该补上？

**Comment by darkhandz** [comment]
两个教程只参考其中一个即可，建议需要触摸板好用的按10.11.6教程，否则上10.12.1比较简单（不需要做DSDT的工作）。

**Comment by Supertramplee** [comment]
hdmi已经正常，声卡多次重建依然无效T T，惊喜的是thunderblot口，hdmi能显示，usb和网卡不能用。。。

**Comment by Supertramplee** [comment]
hdmi已经正常，声卡多次重建依然无效T T，惊喜的是thunderblot口工作正常！不过需要开机的时候就插好才能正常驱动。

**Comment by Supertramplee** [comment]
thunderblot热拔插只有hdmi好用，可能跟驱动有关，系统无法自动挂载设备usb驱动。

**Comment by Supertramplee** [comment]
另外，我的tb口用的是dell自己家的wd15扩展坞，一直没弄明白这个设备接上后是走的usb总线还是tb总线，但是能确认的是这个tb总线的type-c借口是工作正常的！

**Comment by Supertramplee** [comment]
看到另一条留言，同样的问题，睡眠唤醒后tb口无法正常工作。

**Comment by Supertramplee** [comment]
corenel 在他的介绍里写的 TB3/type-C port stiil can't hot-plug. (Waiting for good news from goodwin_c)

**Comment by Supertramplee** [comment]
finally, it worked!!!!......我用了corenel 的驱动更新了一下。。

**Comment by darkhandz** [comment]
额，恭喜了，声卡不能驱动的话，你试试不要aDummy.kext，直接用AppleALC.kext

**Comment by Supertramplee** [comment]
我好像发现问题了，这是我重置驱动缓存的时候到提示：
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext NullEthernet.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext IntelBacklight.kext
kext-dev-mode allowing invalid signature -67030 0xFFFFFFFFFFFEFA2A for kext HackrNVMeFamily-10_12_1.kext
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext CodecCommander.kext
KernelCache ID: 847600C01665DDC2953C593D40771F81


多了一个codeccommander. 没有adummy啊。。。你的有这个问题么

**Comment by darkhandz** [comment]
额……可以多试两次
另外，直接用AppleALC.kext会比较容易。
