### ISSUE TITLE
我怎么这么作啊!

### ISSUE THREAD

**Issue by kandra777** [darkhandz/XPS15-9550-Sierra#16]
黑大大!一直用的挺好 所有配置和软件都搞好了 然后手贱不小心在app store里面安全更新了

然后重启 读进度跳 很慢 我以为又是卡进度 就电源键关机重启 然后开机 就是比较缓慢的走完后半段进度

但是等很久都进不去系统!

想问问有没有办法回滚到更新前的系统啊?别回又要重装吧 麻烦了

**Comment by darkhandz** [comment]
好像是没有回滚的……没试过……
