### ISSUE TITLE
新增的亮度调节更新可以直接用么

### ISSUE THREAD

**Issue by lzt7star** [darkhandz/XPS15-9550-Sierra#17]
新增的亮度调节可以直接用么，acpi里的ssdt-pnlf需要更换么？

**Comment by darkhandz** [comment]
不好意思，我测试得不够多，所以没发现新的调节亮度它有个BUG，重启不能保存亮度……
因为平时我都是下班就盖盖子休眠，回家开盖即用……所以有时5天都不重启一次……
已回退版本了，真抱歉。

**Comment by lzt7star** [comment]
谢谢测试，支持po主
