### ISSUE TITLE
ACHI 下的windows10 磁盘占用率100%

### ISSUE THREAD

**Issue by ImmortalLeaf** [darkhandz/XPS15-9550-Sierra#19]
有没有装黑苹果以后再装Windows10 双系统的？有没有人遇到过和我一样的情况，任务管理器里面看磁盘占用一直是100%，微软官方的做法禁用MSI依旧无效。ssd测速正常，日常使用正常，但磁盘占用率始终为100%，有没有什么解决方案？

**Comment by darkhandz** [comment]
你是怎么安排的分区呢？我是加了一个SATA的SSD，win10安装在这个单独的SSD里。
![default](https://cloud.githubusercontent.com/assets/2143333/21122802/6693edb4-c10f-11e6-90b6-a81e7c78e6b9.png)
