### ISSUE TITLE
体验反馈

### ISSUE THREAD

**Issue by GeekAudio** [darkhandz/XPS15-9550-Sierra#20]
10.11.6和10.12.1前前后后装了10多次，今天装完10.12.1感觉还是很完美的 触摸板难用，好在 手里有一个magic trackpad2（蓝牙触摸板）体验还是非常完美的，声卡也正常了，只是播放音乐合上盖子再打开就没有声音了。不过也没有多大的影响。我的是4k屏，偶尔有一点闪屏，bios 之前用老大推荐的版本，经常卡死。win10表现为蓝屏，换了一下最新的bios 基本没有问题了

**Comment by darkhandz** [comment]
触摸板驱动这个暂时是没办法的了。magic trackpad2……口水……
浅睡眠唤醒无声这个问题也困扰着我，不过平时上班不怎么搞音乐，所以暂时不管它了。
闪屏大家都说是DELL不作为，BIOS不解决……话说我还没升级12月的BIOS，不知道热补丁适配情况。
