### ISSUE TITLE
SSD在PCI0设备的路径

### ISSUE THREAD

**Issue by GeekAudio** [darkhandz/XPS15-9550-Sierra#21]
在哪里查看，win10需要安装硬盘驱动去查看吗

**Comment by darkhandz** [comment]
机型主板相同的话，应该是一样的
![default](https://cloud.githubusercontent.com/assets/2143333/21182217/e2e5dbe2-c23c-11e6-91ff-f197fcfe7c2b.png)

**Comment by GeekAudio** [comment]
在win10下所有驱动都安装了就是没有看到BIOS设备名，win10 企业2016长期服务版
右键此电脑-管理-设备管理器-磁盘驱动器-PM951 NVME -右键属性-详细信息-属性

**Comment by darkhandz** [comment]
NVME的话，应该也是RP09。实在找不到的话，可以试试用AIDA64查看。

**Comment by GeekAudio** [comment]
老大Nvme共存那里 实在是给跪了， 能不能放出您改好的文件，替换一下 执行几行代码就搞定

**Comment by darkhandz** [comment]
[百度云下载](https://pan.baidu.com/s/1kUGOBGV)之后，解压得到一个kext和一个aml，这个aml放Clover/ACPI/patched里，kext放Clover/kext/10.12里。
如果可以用，删除config.plist里面的IONVMe相关补丁项。
