### ISSUE TITLE
Nvme 破解与原生共存

### ISSUE THREAD

**Issue by GeekAudio** [darkhandz/XPS15-9550-Sierra#22]
1.按照教程把生成的hacknvme进行修改保存，
2.用命令把这个文件安装到指定目录
3.把原生文件重命名（nvme.bak->相应名字）
4.根据路径把代码插入SSDT-NVME文件，然后生成aml文件 放到efi分区指定目录
下载10.12.2 升级安装后硬盘引导无法进入系统，u盘引导可以进入（10.12.2），尝试修复硬盘引导 -失败。回滚10.12.1。 操作了两遍 还是无果。指点一下那里错了
ssd 路径用ioreg 命令一点一点找出来的，和您的路径一样

**Comment by GeekAudio** [comment]
每次操作完成都重建过缓存，现在只有共存没完成，其他都做了

**Comment by darkhandz** [comment]
估计是第二步我描述的顺序错了，误导了你们。修正一下：

先把原生NVMe驱动（上面被我们改成了NVME.bak）改名回IONVMeFamily.kext，再用RehabMan的脚本生成破解的HackrNVMeFamily*.kext驱动，修改Info.plist，把IOPCIClassMatch改成：`0x0108ff00&0xFFFFFF00`，然后安装到/Library/Extensions里。清除缓存。

**Comment by GeekAudio** [comment]
老大，这个顺序有影响吗

**Comment by GeekAudio** [comment]
![img_0775](https://cloud.githubusercontent.com/assets/19627926/21222534/49435f02-c2fd-11e6-85c1-89dd6f1addeb.jpg)

**Comment by niceokf** [comment]
u盘引导可以直接进入10.12.2系统

**Comment by niceokf** [comment]
不想再回滚了，累

**Comment by darkhandz** [comment]
看不出来是什么错误引起的，我的一般是AppleALC才会卡这里

**Comment by GeekAudio** [comment]
@RehabMan 更新了

**Comment by darkhandz** [comment]
按脚本参数操作，可以省掉 “我是怎么做的” 里面的第2小步。

**Comment by GeekAudio** [comment]
<img width="978" alt="2016-12-17 4 14 53" src="https://cloud.githubusercontent.com/assets/19627926/21285456/15bea038-c474-11e6-8ec9-b31d568610ef.png">
我在升级完系统后黑屏，强制重启后无法引导进入系统，错误【IGPU】
用u盘引导进入系统后 恢复之前的efi分区文件。可以硬盘进入系统了。重建缓存出现图上错误，
显卡没有驱动成功，进入系统很卡，屏幕亮度部能调节，声卡正常

**Comment by GeekAudio** [comment]
config.plist用的是您的Clover-Finish

**Comment by darkhandz** [comment]
升级完之后，估计还需要用fakeID（0x12345678）来进入系统，然后再次打4K补丁。我没有4K屏，还要靠你自己测试。

**Comment by GeekAudio** [comment]
感激不尽，折腾好了 您说的对劲
