### ISSUE TITLE
 英语指南

### ISSUE THREAD

**Issue by rohinrohin** [darkhandz/XPS15-9550-Sierra#23]
Hey can you post an English guide if it is possible. 

Thanks 

嘿，你可以发布一个英语指南，如果可能的话。

谢谢

**Comment by darkhandz** [comment]
I really want to make an English version, but my poor English won't let me do that.
Sorry about this, but you can refer to [tonymacx86](https://www.tonymacx86.com/threads/guide-dell-xps-15-9550-skylake-gtx960m-ssd-via-clover-uefi.192598/), it's a great tutorial.

**Comment by zhuzhe1983** [comment]
这个哥们貌似是我从tonymacx86给你介绍过来的，哈哈哈

**Comment by darkhandz** [comment]
@zhuzhe1983 额，那你不翻译一下！

**Comment by darkhandz** [comment]
https://www.tonymacx86.com/threads/guide-dell-xps-15-9550-sierra-10-12-2-tutorial.210368/
