### ISSUE TITLE
最新bois问题

### ISSUE THREAD

**Issue by GeekAudio** [darkhandz/XPS15-9550-Sierra#27]
4K 9550 升级bois后  osx 系统 左上角闪 问下怎么降级 我用1.2.16 完美。 只是唤醒后会闪

**Comment by darkhandz** [comment]
左上角闪？没见过……
好像BIOS设置里面有可降级的选项，你自己打开再试试哦，我没试过降级。

**Comment by GeekAudio** [comment]
已经降级好了，不是bios问题，还原了之前的clover就好了

**Comment by darkhandz** [comment]
我大概知道你在说什么了，左上角黑色块闪动是吧……你需要添加一些特殊的东西到config.plist里。
可以查看我的config.plist，搜索AddProperties。
