### ISSUE TITLE
关于killer1535

### ISSUE THREAD

**Issue by TheadoreL** [darkhandz/XPS15-9550-Sierra#29]
killer 1535无线网卡发现不了，不知道有没有推荐的驱动

**Comment by darkhandz** [comment]
Google了一下，似乎没有的。建议更换网卡硬件。

**Comment by darkhandz** [comment]
[参看这里](https://www.tonymacx86.com/threads/faq-read-first-laptop-frequent-questions.164990/)的WiFi问题

**Comment by TheadoreL** [comment]
我也查了不少资料，应该是没救了，之前硬盘问题，我也是直接加了一块sata ssd，这次估计又要换

**Comment by darkhandz** [comment]
嗯，黑苹果有时候硬件没驱动就无解了，早些时期还有用外置360WIFI当网卡用的呢……我也不知道9550机型会有这么多硬件变种

**Comment by TheadoreL** [comment]
刚装好就可以正常使用蓝牙，就是发现不了WiFi，求推荐一款网卡。用自己的rmbp习惯了，帮朋友黑苹果实在是麻烦

**Comment by darkhandz** [comment]
上面提到的帖子有推荐以下几款，请根据自己机型插口选择：

Best choice: BCM94352HMB (or BCM94352Z if your laptop needs NGFF/M.2 2230). Also, the NGFF BCM94350ZAE is a possibility.

Note: BCM94352HMB is easy to find and generally is $20-$30. For BCM94352Z, read here: http://www.tonymacx86.com/yosemite-laptop-support/160258-where-can-i-get-bcm94352z.html. It can be ordered from Dell (phone them) for approx. $20.

Another choice (with 802.11ac) is the BCM94360HMB. It is a bit more native (device-id is supported natively), but also uses 3 smaller antenna connectors than are typical. So a bit more work to install. Same goes for (NGFF) BCM943602BAED if you need an M.2 2230 card.

Be aware that some BIOS implement a so-called "whitelist". A whitelist prevents you from installing cards that the OEM has not deemed compatible. In many cases, you won't know whether your BIOS implements a whitelist until you attempt to replace the WiFi card.

If your laptop implements a whitelist, you may be able to rebrand a supported card to the IDs that your BIOS supports. You can then use FakePCIID.kext to convince OS X of the true identity of the device.

Note that newer laptops do not use half-mini PCIe as NGFF (now called M.2) is becoming more popular. In the case of NGFF, look for BCM94352Z.

**Comment by TheadoreL** [comment]
好的，谢谢
