### ISSUE TITLE
aDummy.kext 不加载

### ISSUE THREAD

**Issue by shixuev5** [darkhandz/XPS15-9550-Sierra#3]
把aDummy.kext放入S/L 重建缓存不加载  其他几个都正常加载 这个没加载 。 重启没有声音 clover尝试fixHda  inject 13 还是不行 最后把aDummy.kext 删了 Clover放appleALC.kext再inject 13 就好了。 但是启动有时候会卡开机。 请问aDummy.kext是怎么弄的？是否具有通用性。

**Comment by darkhandz** [comment]
aDummy是AppleHDA Patcher生成的，具体内容其实就是两部分：
1. 你声卡所对应的两个zlib文件
2. ConfigData注入到Info.plist里你声卡Codec对应的节点

以上两部分我都是从AppleALC的源码来提取的，另外还需要对AppleHDA.kext进行Patch，这些Patches可以在AppleALC的源码你的声卡对应的资源里找到。

总的来说就是，aDummy只是个注入器，如果AppleALC可以驱动你的声卡，理论上你把AppleALC里你的声卡资源提取到aDummy里，Clover加上Patches，注入layout-id（13），就可以了。

**Comment by shixuev5** [comment]
不知道怎么的 。重新弄一遍 aDummy.kext 加载了 现在可以了 。谢谢～

**Comment by darkhandz** [comment]
嗯，有时候清理缓存重启再试一下比较准确……嘿嘿，不知道什么原理
不过深度睡眠后唤醒的话，还是有无声的问题……音量可以调节，可是无声
