### ISSUE TITLE
笔记型用 iMac17,1 喔......

### ISSUE THREAD

**Issue by PMheart** [darkhandz/XPS15-9550-Sierra#31]
想知道 这样做的目的是什么？不想开启笔记型的一些features吗......

**Comment by darkhandz** [comment]
额，跟着大神开了MacBookPro13,1，试用了几天，似乎没有什么感知得到的变化。
再换MacBook9,1试试先。

**Comment by PMheart** [comment]
MBP 不是会有DMI长度上限喔？还是MB91啰 :-)

**Comment by darkhandz** [comment]
嗯，查看 型号标识符 那里不完整，不过目前没有需要升级系统，所以似乎没有什么影响……
也就没管了，明天换MacBook9,1试试。

**Comment by PMheart** [comment]
yes 型号标识符应该是很底层的东西控制的... 不是轻易就能改的 否则在老Mac上限制禁止装新系统就没意义了
额 好吧 错误的 MI 还会影响升级喔... I see.

**Comment by PMheart** [comment]
btw AppleHDA也可以用和NVME一样的解法 MacOS 下直接放一个改过的完整AppleHDA bin
