### ISSUE TITLE
sleep issue

### ISSUE THREAD

**Issue by togbyte** [darkhandz/XPS15-9550-Sierra#33]
Thanks for working on this and sharing it with other hackintosh fans over the world. 

Have you gotten sleep to work? My xps 15 9550 wakes up immediately after it tries to go to sleep. I used your acpi patches and clover, but I could not get it sleep. The same patches and clover work fine in 10.11.6.

**Comment by darkhandz** [comment]
My laptop goes to sleep just as normal.
Close the lid / Apple Icon-Sleep, after about 20s , the laptop power down, power led off. 
Are you using the `Clover-Install` folder's files?

**Comment by togbyte** [comment]
Thanks for the email. I got it working now. For some reason I had to disable the USB Wake Support setting in BIOS to get the sleep working. This is only required when my AC power supply is plugged in. 10.11.6 sleeps fine without this setting disabled even if the AC power is plugged in.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
