### ISSUE TITLE
4k屏请教

### ISSUE THREAD

**Issue by lzt7star** [darkhandz/XPS15-9550-Sierra#36]
我换4k屏，我看到教程里有2步关于4k屏的，请教一下我直接先在1080屏操作第二步，然后换屏重启可以么

**Comment by GeekAudio** [comment]
全程在4K屏幕下操作即可

**Comment by lzt7star** [comment]
好的，我试试

**Comment by zhuzhe1983** [comment]
借地方问下，4k屏的那个操作可逆么？

**Comment by darkhandz** [comment]
@zhuzhe1983 可逆，同目录会存在一个`CoreDisplay.bak`，自行重命名覆盖`CoreDisplay`即可。
