### ISSUE TITLE
黑苹果微信发不出去图片

### ISSUE THREAD

**Issue by ImmortalLeaf** [darkhandz/XPS15-9550-Sierra#39]
请问下有没有人在黑苹果下用mac版微信的？有没有遇到图片发不出去的问题？

**Comment by zhuzhe1983** [comment]
截图发出去是正常的~建议检查下自己的网络

**Comment by darkhandz** [comment]
我这里也正常发送的，没听说过黑苹果还影响发图片…… : ) 

@zhuzhe1983 感谢哥们常帮忙解答issue

**Comment by ImmortalLeaf** [comment]
但是的确不论是学校还是家中的网络(香港和内地)均无法发送图片。。。Windows系统下正常，应该不是网络的问题。微信为mac APP store下载的最新版

**Comment by ImmortalLeaf** [comment]
另外可不可以求一个macOS 10.12.2 的IONetworkingFamily.kext。之前安装过一个usb c网卡驱动可能影响了这一点，希望重置下看看是不是它的问题

**Comment by darkhandz** [comment]
@ImmortalLeaf 我数据崩溃过，恢复到10.12.1了，暂时没有该驱动，看看热心的 @zhuzhe1983 有没有

**Comment by ImmortalLeaf** [comment]
重装了一下微信还是不行。。。相当奇怪。。。而且微信传输文件完全没问题只有图片会出问题，活动监视器中显示图片会上传，有流量，然后会显示一个红色叹号。。。手机上看的确没有发出去

**Comment by zhuzhe1983** [comment]
我也是在10.12.1呢， 换个3G网络看看呢？ @ImmortalLeaf

**Comment by darkhandz** [comment]
应该是楼主个人网络问题

**Comment by Stone-Crown** [comment]
我也遇到了！我2570P 10.11

**Comment by ImmortalLeaf** [comment]
@nalanqinwang 我用了现在新版的clover文件夹（应该是用了新版的smbios）就好了

**Comment by Stone-Crown** [comment]
哪个版本？我用3994没声音

**Comment by Stone-Crown** [comment]
我先升级12看看
