### ISSUE TITLE
MoreKext-10.12.1.zip在何处下载？

### ISSUE THREAD

**Issue by arshcaria** [darkhandz/XPS15-9550-Sierra#4]
请问您在第2步提到的MoreKext-10.12.1.zip在那里下载？

**Comment by arshcaria** [comment]
指的是XPS15-9550-Sierra/MoreKexts-LE这个文件夹吗？这个文件夹下的内容和readme中描述的不太一样。

**Comment by darkhandz** [comment]
真抱歉，本来打算把教程发论坛的，论坛要打包……结果还没上论坛，先在GitHub发了。
没错，文中所有MoreKext-10.12.1.zip都指的是XPS15-9550-Sierra/MoreKexts-LE，已修正readme描述。
