### ISSUE TITLE
dell 5510 i7 6820， sata 512ssd单硬盘，4k屏幕，无法进入安装界面

### ISSUE THREAD

**Issue by soulomoon** [darkhandz/XPS15-9550-Sierra#41]
黑手大神，我看到[issue#9](https://github.com/darkhandz/XPS15-9550-Sierra/issues/9)成功了，我在[issue#32](https://github.com/darkhandz/XPS15-9550-Sierra/issues/32)找到了sierra的安装包。
我尝试使用你的配置安装sierra 10.12.2，但是boot不进去安装系统界面。(刚才版本号打错了)
一直卡在这里，如下图
[图片在这里](https://github.com/soulomoon/dell-5510-OSX/blob/master/IMG_3853.JPG)

**Comment by darkhandz** [comment]
去掉AppleALC.kext 试试

**Comment by soulomoon** [comment]
非常感谢回复 
SSDT-ALC298.aml 这个吗？ @darkhandz

**Comment by darkhandz** [comment]
你安装的是10.12还是10.11？kexts的子目录下有什么驱动？

**Comment by soulomoon** [comment]
我要安装的是10.12 ， 尝试使用你的Cover-install 进行安装

**Comment by darkhandz** [comment]
进入安装界面前要把config.plist修改下，增加一个：

```
<key>FakeID</key>
<dict>
    <key>IntelGFX</key>
    <string>0x12345678</string>
</dict>
```

0x191b0000还要改成0x19268086。

ACPI/patched目录下还要删除SSDT.aml

**Comment by soulomoon** [comment]
现在才发觉原来之前我下载的镜像是10.12.2，
1.在devices节点下加fakeID
2.修改为0x19268086
3.删除SSDT.aml.
在10.12.2下boot不进系统，是不是跟版本有关系？我再去找找，12.1的链接，没有远景账号，所以用不了黑手大大你给的链接

**Comment by soulomoon** [comment]
在这里我有个问题，
0x19268086 不是针对的是HD P530 显卡的吗
i7 6820的集显依然是HD 530。 @darkhandz

**Comment by soulomoon** [comment]
报告一下
我把镜像更换为10.12.1带COLOER版本的
[10.12.1](http://macx86.cn/macos/4430.html)
transmac 释放到硬盘
CLOVER原本的删掉
把clover-install的包复制过去，改为CLOVER 。
1.在devices节点下加fakeID
2.修改为0x19268086
3.删除SSDT.aml
依然卡在同样的地方
我有一个配置能进入安装点，我正在把东西一个个更换试图找到是哪里的问题

**Comment by darkhandz** [comment]
额，那不用改0x19268086了。
可以[以这一份为最精简](https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/config_HD520_530_540.plist)版本，然后从我的config.plist复制一些必要的东西过去尝试。比如NVME补丁，DSDT补丁。

**Comment by soulomoon** [comment]
感谢黑手大神 经过反复的尝试终于定位到原因了 kexts的问题，现在反复更换看看哪个是原因
------------分隔符-------------_-////
@darkhandz 
经过惨绝人寰的二分穷举法，终于定位到最终原因， FakeSMC.kext，
我更换了一份之后就能boot上去了

为了验证是不是git下来的FakeSMC.kext损坏了的原因，
我又在这里git了一个下来，依然有问题，
我上传了一份我的dell 5510可以使用的 FakeSMC.kext上来这里
[点这里](https://github.com/soulomoon/dell-5510-OSX)

**Comment by soulomoon** [comment]
新的问题来了 安装完成后boot进去设置用户名，发现键盘无法驱动？ @darkhandz 
------------分隔符-------------_-////
又找到原因了，是因为kext- - 我也看看具体是哪里

**Comment by darkhandz** [comment]
你可以下载最新的VoodooPS2Controller来代替我默认的那个试试，网址在教程开头有。

**Comment by soulomoon** [comment]
好的 成功了。 非常感谢 @darkhandz

**Comment by soulomoon** [comment]
这里还有一个问题 ， 进入桌面安装LE的驱动时候产生大量的syntx error near line 1？
不知道是由什么引起的呢？
`Can't read info dictionary for aDummyHDA.kext: IOCFUnserialize: syntax error near line 1.`
`Can't read info dictionary for CodecCommander.kext: IOCFUnserialize: syntax error near line 1.`
`Can't read info dictionary for IntelBacklight.kext: IOCFUnserialize: syntax error near line 1.`
`Can't read info dictionary for NullEthernet.kext: IOCFUnserialize: syntax error near line 1.`
都是这几个在循环

**Comment by darkhandz** [comment]
有点像文件损坏了……我没遇到过这个问题呢。

**Comment by soulomoon** [comment]
我重新下一份试下

**Comment by darkhandz** [comment]
如果你是用U盘传送，建议换一个U盘试试。

**Comment by soulomoon** [comment]
我好像明白了。 因为是在win下git下来的， 好像win的git自动修改换行符号为windows的然后全部第一行就出错0 0  好坑。 快点换个linux环境重来。。。

**Comment by darkhandz** [comment]
建议Download zip……

**Comment by soulomoon** [comment]
thank you  @darkhandz ,every thing is fine now,
for the followers
 just be aware of using git under windows to do the installation, please use download zip instead
