### ISSUE TITLE
为了使用HDMI， 我把SIMBOIS信息改成了macbook9.1 现在没有办法进入系统求帮

### ISSUE THREAD

**Issue by soulomoon** [darkhandz/XPS15-9550-Sierra#42]
为了使用HDMI， 我把SIMBOIS信息改成了macbook9.1 现在没有办法进入系统求帮

**Comment by soulomoon** [comment]
iMac 14 get me to work just fine with hdmi now

**Comment by darkhandz** [comment]
改了MacBook9,1要删除ACPI/patched里面的SSDT.aml再重启

**Comment by soulomoon** [comment]
谢谢 可以进入mb9，1

**Comment by darkhandz** [comment]
@soulomoon https://github.com/wmchris/DellXPS15-9550-OSX 这边有不少干货，可以试试，晚点我再集成

**Comment by soulomoon** [comment]
好的 非常感谢
