### ISSUE TITLE
关于config.plist中的NVME补丁

### ISSUE THREAD

**Issue by skinnyshy** [darkhandz/XPS15-9550-Sierra#47]
请问
补丁打完了，现在要把EFI分区里Clover的config.plist里面的所有关于IONVMeFamily的补丁删除，请自行用Clover Configurator挂载分区并操作。实在懒的话，可以用我GitHub的Clover-Finish文件夹里的plist覆盖你的。

在config.plist（是CLOVER-install中的config.plist）中为何搜索不到IONVMeFamily

**Comment by skinnyshy** [comment]
@darkhandz  求助，现在装完起来是禁止运行的标志伴有乱码（-v参数都是乱码）
![qq 20170122164221](https://cloud.githubusercontent.com/assets/12553514/22181202/d0cd81aa-e0c1-11e6-808c-bb5be073fa39.jpg)
![qq 20170122164233](https://cloud.githubusercontent.com/assets/12553514/22181203/d0f1c2a4-e0c1-11e6-9459-2f7e8f8817ed.jpg)

**Comment by skinnyshy** [comment]
试了好多次都是卡这，只要装完系统后，装完驱动重启就这样 T T

**Comment by darkhandz** [comment]
请确保下载的是最新的github的文件（11天前更新），然后关于NVME的驱动不用再安装到/L/E里了。config.plist只要用Clover-Install里面的那个就好了，里面没有IONVMe相关的补丁了。

**Comment by darkhandz** [comment]
教程描述已修正，不用再做这步了：6. 给NVME驱动打补丁（本步骤请略过，已做好了共存）

**Comment by skinnyshy** [comment]
@darkhandz  辛苦你了，我重新做一遍试试，提前拜个早年，新年快乐！

**Comment by darkhandz** [comment]
@skinnyshy 明天还要去医院，看来是没办法过好年了  😭

**Comment by skinnyshy** [comment]
![qq 20170122201813](https://cloud.githubusercontent.com/assets/12553514/22182417/f036b50c-e0df-11e6-9b3b-4830699a39c1.png)

@darkhandz  生病了吗？ 祝一切顺利，身体安康啊。

实在不好意思这时候还麻烦你，为何我无法加载“BrcmPachRAM2”啊，只要它在kexts里启动就会循环显示这个

**Comment by darkhandz** [comment]
不明原因，没试过这样的提示哦，你可以先去掉看看。
搜索了一下，这个问题在这里7月已经被解决了：https://bitbucket.org/RehabMan/os-x-brcmpatchram/commits/66066f6613f0d3e2c1063ef1e8b7478f3828d2fb#general-comments

请确保你下载的是最新版的：[下载地址](https://bitbucket.org/RehabMan/os-x-brcmpatchram/downloads)

**Comment by skinnyshy** [comment]
@darkhandz 还没来得及试，启动分区(ESP空了)就崩了 T T 之前的分区（windows中的D盘）也没了 只剩下一个windows分区，我先抢救一下让windows回来

**Comment by skinnyshy** [comment]
@darkhandz  更新  使用最新版的BrcmPachRAM2 没有问题，替换Clover\kexts\10.12下的BrcmPachRAM2.kext就OK了。
还有就是蓝牙依旧不可用，耳机放音不正常，hwmonitor检测部到硬件温度，是和FAKESMC有关吗

**Comment by darkhandz** [comment]
@skinnyshy fakesmc请自行更新到1月份版本（并包括4个附加的检测驱动），即可检测到。耳机声音可试试 gujiangjiang 同学的AppleALC，不过AppleALC有卡在开机Logo的风险。

**Comment by skinnyshy** [comment]
安装完下载的fakesmc的几个驱动后无法启动，删除后依然提示如下，这个画面之后就大大的禁止运行标志 
![qq 20170123143507](https://cloud.githubusercontent.com/assets/12553514/22193906/cc25431e-e179-11e6-9a64-68ecdd027411.png)

**Comment by darkhandz** [comment]
那就用回原来的fakesmc试试，不要其他任何sensor的kext。

**Comment by skinnyshy** [comment]
@darkhandz 我也奇怪了，下午都试过了，从RehabMan那里下载的驱动都删了还是一样，我回想了所有操作的步骤，想不出其他的了，和我最上面出现的情况一样，用U盘一样启动不了。 不行我就重新来过吧T  T

**Comment by skinnyshy** [comment]
![qq 20170123231555](https://cloud.githubusercontent.com/assets/12553514/22209575/f60ee386-e1c1-11e6-9b36-98b8f12fc399.jpg)

重新安装又卡这里了。
![image](https://cloud.githubusercontent.com/assets/12553514/22209624/2242eea2-e1c2-11e6-82e8-fdd45434a5c9.png)

**Comment by skinnyshy** [comment]
![img_3042](https://cloud.githubusercontent.com/assets/12553514/22283658/6ebda6fc-e31e-11e6-9d2a-d8b08dc5ad3d.JPG) 安装卡这里，什么情况


____________________________________________
好像和之前硬盘里的EFI分区的clove内容有关，我在win10下挂载硬盘EFI分区，用新的config.plit和kexts内容替换后就可以过了

**Comment by darkhandz** [comment]
额，你EFI太多的话，在BIOS确定一下哪个做第一启动。
