### ISSUE TITLE
无法关机

### ISSUE THREAD

**Issue by GeekAudio** [darkhandz/XPS15-9550-Sierra#49]
每次关机都会自动开机 系统从10.12.2升级到10.12.3 严格按照教程操作，文件是你提供的最新的（一直跟着您更新），4K屏

**Comment by darkhandz** [comment]
我也刚刚升级完10.12.3，试试关机，正常…… @gujiangjiang 同学也遇到关机变重启的问题，也许你们可以交流下……
我还是Clover 3899，Hackr驱动还是10.12.1的版本（放在Clover里了）

**Comment by gujiangjiang** [comment]
拔掉USB-C的设备就行了，插着会无法关机，普通USB接口不受影响

**Comment by GeekAudio** [comment]
@gujiangjiang 的确是这样，感谢您的回复
