### ISSUE TITLE
找不到硬盘

### ISSUE THREAD

**Issue by TheadoreL** [darkhandz/XPS15-9550-Sierra#5]
为什么启动安装的时候找不到内置的硬盘呢，AHCI也打开了

**Comment by darkhandz** [comment]
确定你安装的是10.12.1哦，因为我config.plist里面的Patches是针对破解10.12.1的原生NVMe驱动的

**Comment by TheadoreL** [comment]
是12.1呀，我用我的mac前两天在appstore下载的原版。我用u盘安装的，用的是install的plist

**Comment by TheadoreL** [comment]
在osx安装器里看不到内置硬盘，然后磁盘工具里也看不到，磁盘工具显示只有U盘，其他应该都正常的。问一下刚刚把BIOS也更新了，还是不行

**Comment by darkhandz** [comment]
这就尴尬了……你的硬盘是什么型号？我看得把NVMe驱动共存部分的东西给你。
你先看看那部分的教程，去Windows设备管理器查看你的NVMe所在。或者你的XPS目前有黑苹果的话，用ioreg查看NVMe的路径，然后我给你做一个NVMe的破解驱动。

**Comment by TheadoreL** [comment]
我现在没有黑苹果，我去windows找一个给你看吧

**Comment by TheadoreL** [comment]
这是windows上看到的ssd的硬件路径SCSI\DISK&VENNVME&PRODPC300NVMESK_HY\5&3A0E52E6&0&000000
github 没法传图，我传在了我的博客上您看一下
https://aloha.one/some-problems/

THX

**Comment by TheadoreL** [comment]
这是nvme的bios id
_SB.PCI0.RP09.PXSX

**Comment by darkhandz** [comment]
[百度云下载](https://pan.baidu.com/s/1kUGOBGV)之后，解压得到一个kext和一个aml，这个aml放Clover/ACPI/patched里，kext放Clover/kext/10.12里，然后再进安装试试
对了，config.plist你可以采用Clover-Finish里面那个。

**Comment by TheadoreL** [comment]
我试了还是不行哎，感觉整个SSD都没有挂在进来，问一下，怎么改plist文件，强制挂载硬盘呢

**Comment by darkhandz** [comment]
如果你的SSD是NVMe协议的，在没有破解原生驱动的情况下，苹果系统只会识别他们自家采用的SSD，不会识别任何第三方的。
破解补丁就是为了去除这个限制，让系统识别所有其他第三方的NVMe SSD，成功案例有很多，SM951、PM951、950 pro、XG3……不知道你的为什么不成功，只能建议再爬贴看看了

**Comment by TheadoreL** [comment]
我看了一下  你的plist里似乎没有 <key>IOPCIClassMatch</key>这个节点，我准备添加试试，如果成功到时候给你说下吧

**Comment by mayknight** [comment]
@TheadoreL 
虽然我的硬盘的是ssd，但安装的时候这个问题我也遇到了（刚好，我也是appstore下载制作的）
我解决的方法是：F2把EFI启动项删除整理了一下。BIOS-（Boot Sequence - Boot List Option）
把新做的u盘做为第一启动项，删除其它的。
具体因为啥，我也不会清楚。我估计可能是之前安装10.11.6 的残留？
你试试看:)

**Comment by TheadoreL** [comment]
@mayknight 我这是台新的电脑，原来只装了windows，现在引导也只有windows，我试试吧

**Comment by TheadoreL** [comment]
@mayknight 清楚windows引导我也试了，还是不行，我去看看帖子吧，不过都是讲的启动后修改，但这个对我没必要啊

**Comment by mayknight** [comment]
@TheadoreL 
刚才仔细的回忆了一下，在制作安装u盘的时候，我修改了config.plist (用的macosx自带的文本编缉器）保存之后，出现了那个问题。后来改用其他编缉器做的修改，并且做了我上面的那方法。具体是那步起的作用我实在不了解。

**Comment by TheadoreL** [comment]
@mayknight 我用的是sublime3，现在还是这个问题。我打算去试试上一个版本的10.12，可能是因为最新的版本的问题。

**Comment by lzt8876** [comment]
@TheadoreL 难道不支持海力士的ssd？

**Comment by lzt7star** [comment]
@TheadoreL 修改最好用 plistedit pro 或 clover configurator，不然容易出错

**Comment by darkhandz** [comment]
@TheadoreL  SATA-100-series-unsupported.kext 这个驱动可以试试。

**Comment by TheadoreL** [comment]
我最后的解决办法是，加了一块sata ssd，已经不指望NVMe了
