### ISSUE TITLE
重装macOS系统

### ISSUE THREAD

**Issue by ImmortalLeaf** [darkhandz/XPS15-9550-Sierra#50]
请教一下如何在不影响同硬盘另一分区的windows的情况下重新格式化安装osx系统？使用usb安装在重启之后就会报错无法继续安装。有没有大大有过类似经验的？

**Comment by darkhandz** [comment]
报什么错呢？

**Comment by ImmortalLeaf** [comment]
@darkhandz 具体的不太记得了，是osx安装器报错不是clover报错。大概就是无法继续安装osx的意思。

**Comment by darkhandz** [comment]
我遇到过一次，再重新安装一次就好了
