### ISSUE TITLE
升级10.12.3成功的一点经验

### ISSUE THREAD

**Issue by bsns** [darkhandz/XPS15-9550-Sierra#51]
提醒我升级，我没有完成破解驱动的那一步（第一次尝试，完全没有经验），升级验证失败，我想着升级失败就重回linux的心态试了一下，从官网下载了升级包，直接双击安全，重启成功。
另外？比如clover-install更新了，我是不是要重新安装clover那个流程，再拖动文件夹之类的？

**Comment by darkhandz** [comment]
不用，你跟着我的commit记录看看我改了什么，对着操作就行了。
比如我写到：更新了xxx.kext，你可以自己去下载xxx.kext。
比如commit的对比里出现我对config.plist有修改，你可以看我修改了什么，对着自己的config.plist修改就好了。
