### ISSUE TITLE
想用iService的话SMBIOS用什么会好一点？

### ISSUE THREAD

**Issue by iam-Justin** [darkhandz/XPS15-9550-Sierra#52]
还有就是，更改SMBIOS后，系统关于里变了，但某些软件还是会识别到iMac7,1，（如Mactracker和Clover Configurator的里Rt Variables点Calculate）不知道是为何。

**Comment by iam-Justin** [comment]
换了MB9,1 没有Power Nap了，改回来也没有了。。。

**Comment by darkhandz** [comment]
用IOReg查看一下机型，请确定SMBIOS信息是否填写完整齐全哦。
需要支持电源管理的某些SMBIOS并配合SSDT.aml才可以有PowerNap。

额，我个人也不用iService，所以不太清楚哪个比较好……请自行爬贴呢。
