### ISSUE TITLE
热补丁如何使用？有详细的中文教程吗？

### ISSUE THREAD

**Issue by YaHue** [darkhandz/XPS15-9550-Sierra#53]
如题

**Comment by darkhandz** [comment]
额，没人翻译……不想了解原理的话，直接用就可以了……以前的DSDT.aml是不通用的，现在Hotpatch的aml是几乎通用的（配合config.plist）。

**Comment by YaHue** [comment]
主要是没看太懂我要把 DSDT-HotPatches文件夹里的文件放到哪里呀？

**Comment by darkhandz** [comment]
基本的DSDT知识还是要懂的，dsl编译后变成aml，aml才是有用的，dsl是为了未来还需要编辑的情况下保留的。
所以，DSDT-HotPatches对你来说没用，除非你知道里面的dsl的代码的确切意思。
Clover-Install是成品，用它里面的东西就可以了。

建议有空时自行学习一下pcbeta论坛里DSDT相关的基本知识。

**Comment by YaHue** [comment]
3q已经看懂了
