### ISSUE TITLE
有关最新版本clover下双系统问题，求助

### ISSUE THREAD

**Issue by kandra777** [darkhandz/XPS15-9550-Sierra#58]
如题，替换了最新版clover，没动声卡方面的东西。win10系统为1607，mac为12.3
clover开机引导能找到win10和mac，进入mac没有任何问题
问题：引导进入win10，出来dell logo 然后下面转圈 然后屏幕变黑 下面转圈 然后就是不停转圈 

ps：上网查了一些资料，可能是驱动问题。我想问问 是不是因为mac下禁用了n卡 所以进入win10时会有影响？

本人小白，希望各位大大不吝赐教

**Comment by darkhandz** [comment]
当你重启电脑的时候，所谓的`mac下禁用了n卡`已不复存在，不会影响win10的，我倒是听过mac下的蓝牙会影响win10的蓝牙……
我等下试试进win10

**Comment by kandra777** [comment]
我是看到 clover引导界面 option里面有个 boot arg 那个里面有个禁用n卡的参数 我才不确定是不是有影响

又不改按回车删除 怕影响mac的正常使用 

对了，我是单硬盘 双系统 硬盘是三星 nvme

**Comment by darkhandz** [comment]
clover引导界面 option里面的更改是临时性的，你可以都试试。
下次再启动进入这个option界面时，又会变回config.plist里面定义的默认值。

**Comment by kandra777** [comment]
还是不行，用了win的原版iso高级射设置 选择了启动项修复都不行 不知道黑手大大的win10能进去吗？
能的话能把你efi里面的boot还有micosoft文件拷给我吗？

**Comment by GeekAudio** [comment]
win pe 修复一下efi分区引导，我就是这样操作的，昨天efi格式化，备份恢复无法启动win

**Comment by darkhandz** [comment]
刚试了，我的win10是14393，正常启动。
我的是双硬盘双系统，可能并不适用于你。

链接: https://pan.baidu.com/s/1o7RClh4 密码: dsar

**Comment by kandra777** [comment]
不行 版本不一致

**Comment by GeekAudio** [comment]
进入winpe 找到win磁盘  windows/boot/efi

**Comment by kandra777** [comment]
@niceokf pe下可以访问efi分区 不知道应该如何修改 boot和micosoft文件夹都是装好windows后直接从efi提取出来的 你说的去windows/boot/efi里面，我不知道是要拿什么文件？还是要做什么？麻烦说仔细点 我确实小白一枚 然后我有点不确定到底是efi引导问题还是别的问题 因为我引导界面是可以看到win10系统的 不过启动后 无限转圈 进不去系统

**Comment by kandra777** [comment]
@niceokf 能加你qq吗？
我截图你可能交流的会好点

**Comment by kandra777** [comment]
@niceokf 我qq49256440

**Comment by kandra777** [comment]
反馈一下
之前不能进入win10不是引导问题。
因为我的win10是低版本升级到1607的 所以可能有些未知问题 
重新格式化win10的分区然后用1607的镜像重新安装win10后，所有问题都好了。支持win10快速启动
感谢大家的帮助

**Comment by darkhandz** [comment]
@kandra777 ok，close
