### ISSUE TITLE
触控板双指放大缩小手势

### ISSUE THREAD

**Issue by ImmortalLeaf** [darkhandz/XPS15-9550-Sierra#59]
请问各位大大有没有谁用过可以启用捏合放大缩小手势的触控板驱动？试了本文的，@syscl 的VoodooPS2Controller以及AppleSmartTrackpad均不行。常用Photoshop修图所以急需此功能

**Comment by darkhandz** [comment]
@ImmortalLeaf 建议买个强劲的鼠标（MX Master）或者买个苹果触摸板

**Comment by niceokf** [comment]
@ImmortalLeaf  两个方案，
1，罗技鼠标随随便便一个一百多点的都能有自定义功能，例如m545
2，淘宝买个触摸板2代的400左右

**Comment by syscl** [comment]
常用修图用笔记本触摸板, excuse me??

我的版本和AppleSmartTouchPad都支持缩放 只是实际体验并不好 很容易误操作（缩放）所以禁用掉了。你可以自己手动开启.

syscl
