### ISSUE TITLE
关于制作安装盘的几个问题

### ISSUE THREAD

**Issue by arshcaria** [darkhandz/XPS15-9550-Sierra#6]
谢谢您的教程，在实施过程中我有几个疑问想请教：
1. 在第2步中您说“如果你没有硬盘Clover，那就删除U盘EFI分区里面的EFI文件夹，用我的EFI文件夹代替”，请问您指的“我的EFI”是哪个文件夹呢？我在repo中没找到名为EFI的文件夹。
2. 如果您指的EFI文件夹是repo中的CLOVER-Install或者Clover-Finish，那请问如何怎么使用呢？直接复制替换到U盘EFI\CLOVER文件夹之下吗？需要改动或删除U盘次文件夹下的原有文件吗？
3. 您提供的CLOVER-Install或者Clover-Finish是已经包含热补丁了吗？

谢谢。

**Comment by darkhandz** [comment]
1. 又行文错误了……sorry，"如果你没有硬盘Clover，那就删除U盘EFI分区里面的Clover文件夹，用我的Clover文件夹代替。"
2. 直接删除U盘EFI\CLOVER，复制我的Clover文件夹代替它（Clover-Install改名为Clover）
3. 热补丁在CLOVER-Install里面了，Clover-Finish是一些零碎的文件，按教程做完的话，可不必理会此文件夹
