### ISSUE TITLE
触摸板、声音的几个问题

### ISSUE THREAD

**Issue by arshcaria** [darkhandz/XPS15-9550-Sierra#7]
刚刚已经成功安装sierra到xps 9550，谢谢您的文章。
现在还有几个问题想要请教：
1. ~~没有声音，似乎是声卡没有正确被驱动？~~ 安装了一个网易云音乐之后有声音了...无比奇怪...其他设置没有动过
2. 触摸板不支持某些手势
    * 支持的：双指上下滑动（滚动窗口内容），三指上下滑动（多任务），三指左右滑动（切换全屏）
    * 不支持的：双指缩放（比如缩放网页、图片），双指旋转（比如旋转图片），两指左右滑动
3. 触摸板的双指**大幅度**滚动网页或其他页面时不太顺滑，经常会卡顿停止

请问作者您是怎么解决的？

谢谢。

**Comment by darkhandz** [comment]
没有声音的问题，Issue里的另外一位同学也遇到了，重启过莫名其妙又好了……

黑苹果的触摸板驱动目前分为两个比较出名的：
1. [ELAN, FocalTech and Synaptics (Smart Touchpad) Driver](http://forum.osxlatitude.com/index.php?/topic/1948-elan-focaltech-and-synaptics-smart-touchpad-driver-mac-os-x/)
2. [Voodoo-PS2-Controller](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller)

在10.11.6的时候，前者表现得比较好，但是如今在10.12下，两者都还有问题。
如你看见的，我采用了VoodooPS2Controller驱动，这个一个经过修改的版本，修复了CapsLock按键的问题，目前表现比ELAN的好一点。

当然了，对比苹果原生的触摸板，第三方个人开发的还是相距甚远（时间，精力，硬件API匹配……）。建议不要期望太多……
9550的触摸板我在Win10用起来也是行云流水……到了OSX……唉！只能说，目前我还是依靠鼠标。
