### ISSUE TITLE
请教几个问题...

### ISSUE THREAD

**Issue by zhaoweizhong** [darkhandz/XPS15-9550-Sierra#75]
你好我这里有几个问题（10.12.2）：</br>
1.触控板手势无法使用，我用的是RehabMan的VoodooPS2Controller</br>
2.亮度无法使用键盘调节</br>
3.耗电奇快无比，不到一个半小时就剩3%了，而且我还没开满亮度，不是4K屏
4.Caps Lock键无法使用，一按Caps Lock就卡死</br>
PS：我已经按你的说明对DSDT打上了按键控制亮度补丁和屏蔽独显，也执行了CPU变频的操作。
求解！！:)

**Comment by darkhandz** [comment]
额，10.12.1 （就是这个教程）的话，不需要你打任何DSDT补丁的……直接用我Clover文件夹里面的东西，CPU变频也不需要，有HWP了。
手势的话，基本的三指上下应该还是可以的，你按教程里推荐的syscl的试试（会有更多手势），我教程里的这个我一直在用的。
Caps Lock和VoodooPS2Controller有关，还是同上，我的用了都是正常的。
亮度调节和键盘驱动也是有关，还是同上，正常的。

请首先确保你是按这份教程来的，而不是按10.11.6的教程来的。

电量我大概3个多小时耗尽。1080P，4-5格亮度，写代码。

**Comment by zhaoweizhong** [comment]
我是自己根据远景的各种贴子装好，然后搞了很久之后才发现你这个GitHub....我先试试你的Clover吧

**Comment by zhaoweizhong** [comment]
这次用你提供的Clover启动，亮度问题和Caps Lock解决了，触控板手势还是有问题，连两指放大都不支持，耗电还没测试。怎么办呀

**Comment by darkhandz** [comment]
@zhaoweizhong 两指放大这些似乎不是那么精确的，不能和原生的比呀，我觉得Voodoo是为了尽量支持多的触摸板能用，并没有针对某一款触摸板进行特别的精细开发，所以，这些驱动终究是很难达到理想中和原生比肩的程度，我是用鼠标的……

**Comment by zhaoweizhong** [comment]
好吧谢谢~
