### ISSUE TITLE
M5510升级到10.12.4以后亮度无法调节

### ISSUE THREAD

**Issue by solvar0719** [darkhandz/XPS15-9550-Sierra#77]
目前没有发现其他问题

**Comment by krim404** [comment]
related: https://github.com/RehabMan/OS-X-Intel-Backlight/issues/4

**Comment by krim404** [comment]
fix: https://github.com/wmchris/DellXPS15-9550-OSX/commit/e5551c25be7069367278156b9ad8690382cd4e10

**Comment by Jeremyye114** [comment]
@wmchris Thank you very much It is perfect and work well~

**Comment by Funnyang** [comment]
据说删除IntelBacklight.kext 就好了

**Comment by Jeremyye114** [comment]
@Funnyang  但是删除后亮度等级很差，不能变的很暗，wmchris的有13级可以调～～～差不多可以跟mac的相比

**Comment by solvar0719** [comment]
@Jeremyye114 可以简单描述一下如何使用wmchris的fix吗？需不需要删除intelbacklight?

**Comment by Jeremyye114** [comment]
@scottsanett 要删除intelbacklight的， 替换他的SSDT-Config.aml  SSDT-PNLF.aml  ， L／E放AppleBacklightInjector.kext 修复权限 ，我换了他的config，虽然不知道又无关系～重启～我这边测试有13格，在朋友那测试也是
[未命名文件夹.zip](https://github.com/darkhandz/XPS15-9550-Sierra/files/887761/default.zip)

**Comment by gemini11317** [comment]
@Jeremyye114 可以详细说一下怎么操作吗？怎么替换SSDT-Config.aml SSDT-PNLF.aml呢？我也遇到了不能调节亮度的问题，谢谢

**Comment by solvar0719** [comment]
@Jeremyye114 我之前除了替换config.plist其他事情都做了，并没什么卵用，直到刚刚在clover configurator里面的smbios里把macbook pro换成iMac17,1，替换三码，钩上mobile，重启以后才可用。

@gemini11317 首先删除intelbacklight.kext，你装在哪就在哪删掉，然后在你自己的clover文件夹下用Jeremyye114提供的文件夹里的SSDT-Config.aml和SSDT-PNLF.aml替换，用kext utility安装applebacklightinjector.kext，最后一定要看看你的clover config.plist的smbios里型号是什么，如果是除了iMac 17,1以外的型号要改成17,1，如果之前有白果三码注入，改成imac之后替换即可。

**Comment by gemini11317** [comment]
@scottsanett我看了一下我的clover／acpi/patched这个文件夹是空的我直接将Jeremyye114提供的的那些都复制进去可以吗？还有能不能劳烦您给个联系方式，我对怎么改smbios不是很懂

**Comment by krim404** [comment]
它可能您必须重做注入kext生成，这包含可能与您不同的显示的ID。

its possible you have to redo the injection kext generation, this contains an ID for a display which might be different for you. see:
https://github.com/wmchris/DellXPS15-9550-OSX/tree/master/Additional/PatchAppleBacklight_v2

**Comment by solvar0719** [comment]
@gemini11317 文件夹是空的就有点尴尬了，想必你用的应该不是darkhandz的安装教程，直接全部复制可能会有问题，但这已经在我理解的范围之外了…
关于smbios，你有下clover configurator这个app吗？直接打开你就会看到smbios这个标签。
P.S. scottsanett@gmail.com 邮件和Messages都可，

**Comment by Jeremyye114** [comment]
@scottsanett 其实我这边17.1和13.3都无问题，应该是wmchris的config里面添加了东西吧，不好说，突然间自己的现在可以保存亮度了，原本他的貌似开机亮度不能保存，也不知道为啥

**Comment by Jeremyye114** [comment]
@gemini11317 或者尝试用wmchris的PatchAppleBacklight_v2

**Comment by solvar0719** [comment]
@Jeremyye114 这就很神奇了，我沿用他的CLOVER文件夹直接开不了机🌚 目前还是不能保存亮度，好像和NVram有关？

**Comment by Jeremyye114** [comment]
@scottsanett 我也是，他的acpi全换我也挂了～～～估计他的apci不适合我～～

**Comment by solvar0719** [comment]
@Jeremyye114 只用他的config.plist也挂了🌚 还是不折腾亮度保存了…

**Comment by Piping** [comment]
使用 [Brightness](http://bergdesign.com/brightness/#download) 这个软件就可以调节亮度,IntelBacklight 没坏, 但是键盘按键和功能失联了

**Comment by sysrq-reisub** [comment]
Sorry I just speak english, so for our computer the solution is to re-compile the dsdt with the patches you modified?

**Comment by solvar0719** [comment]
@Lukypie You need to first remove IntelBacklight.kext from wherever you installed it, then download 未命名文件夹.zip provided by Jeremyye114, extract it and replace SSDT-Config.aml and SSDT-PNLF.aml in your clover patched directory with the ones you just extracted, and finally install AppleBacklightInjector.kext to /S/L/E or /L/E and rebuild cache. Reboot and you should be able to have 13 (major) grades of brightness,

**Comment by krim404** [comment]
未命名文件夹.zip is a old version of my compiled files. You can use the new version which also supports FHD.

https://github.com/wmchris/DellXPS15-9550-OSX/tree/master/10.12/Post-Install/LE-Kexts/AppleBacklightInjector.kext

you only need to replace 3 files:
ACPI/patched/SSDT-Config.aml
ACPI/patched/SSDT-PNLF.aml
Post-Install/LE-Kexts/AppleBacklightInjector.kext

And delete IntelBacklight.kext

no need to replace the whole clover patched or the config.plist.

**Comment by sysrq-reisub** [comment]
Sorry if I keep bothering, It still doesn't work for me.
So the things I've tried is:
Copy the SSDT's to ACPI/patched
Install in /L/E/ AppleBackLightInjector, and deleting IntelBacklight.kext
Deleting kext caches, rebooted, used Kext Utility to fixing permission and rebuilding cache again, rebooted again
Added the BacklightInjector patch to clover
Deleted kext caches, used Kext Utility to fixing permission and rebuilding cache again. Rebooted again.

Clover plist
![schermata 2017-05-13 alle 18 40 59](https://cloud.githubusercontent.com/assets/7904559/26027317/52f31b26-380c-11e7-9a6d-a9f38220b1d9.png)

Clover EFI kext 10.12 folder
![schermata 2017-05-13 alle 18 42 50](https://cloud.githubusercontent.com/assets/7904559/26027322/5d98bc2a-380c-11e7-9278-9eca821e1267.png)

kextstat log
![schermata 2017-05-13 alle 18 41 23](https://cloud.githubusercontent.com/assets/7904559/26027325/72d9fd74-380c-11e7-9547-45ff99879bf5.png)

SLE and LE piping output with grep with the keyword "Back"
![schermata 2017-05-13 alle 18 42 08](https://cloud.githubusercontent.com/assets/7904559/26027327/80ca4984-380c-11e7-83b6-b32475bc5350.png)

LE Folder
![schermata 2017-05-13 alle 18 41 45](https://cloud.githubusercontent.com/assets/7904559/26027331/909e459a-380c-11e7-9acb-fb27e2273f15.png)





Forgot to mention I have an i5 XPS 15 9550 with fhd screen

**Comment by krim404** [comment]
1st possible bug: use of wrong version, use the version from my repo
2nd possible bug: forgot to update kext cache after installation.
3rd possible bug: https://github.com/wmchris/DellXPS15-9550-OSX/blob/master/Tutorial_10.12_Step7.md#display-backlight-control-not-working

**Comment by Piping** [comment]
@Lukypie Simply put, remove IntelBackIight.kext and it will work automatically. IntelBackIight is broken in 12.4. You don't need to install anything.

**Comment by krim404** [comment]
No installation result in very VERY bad control with lowest brightness at 50% real brightness.

**Comment by solvar0719** [comment]
@Lukypie Like wmchris said the newer version should work with FHD machines. Even so you may want to modify the values in the info.plist of that kext to make it adapt to your panel's brightness. Before I modified the values to match my panel, the lowest was about 30% real brightness and would not go down from there, and the brightest was on the 11th *major* level and would not go up. The values are not evenly distributed, which was pretty confusing as well.

**Comment by krim404** [comment]
thats also done in the newest version. Tried my best to make it even and utilize the full range of 1% - 100% (of course brightness is something everyone experience different, so it may be not perfectly even distributed for you)
