### ISSUE TITLE
USB-C无法热插拔？

### ISSUE THREAD

**Issue by solvar0719** [darkhandz/XPS15-9550-Sierra#82]
现在运行的是10.12.4，CLOVER文件夹基本沿用（除了用VoodooHDA替换AppleHDA，ApplePS2SmartToupad替换VoodooPS2）。最近发现用Dell自家的USB-C转换插头，只能两次热插拔，第三次插上以后系统不识别，必须重启才能使用。在System Information下的thunderbolt页也显示No hardware was found. 这是正常情况吗？

**Comment by GeekAudio** [comment]
我的da200也是这样。

**Comment by krim404** [comment]
see https://github.com/wmchris/DellXPS15-9550-OSX/issues/7 for a possible fix.
