### ISSUE TITLE
dell m5510 求助

### ISSUE THREAD

**Issue by zhuzhe1983** [darkhandz/XPS15-9550-Sierra#9]
大神你好，我是dell m5510，外观和大部分配置都跟9550差不多的，已经用您的配置安装进了系统，但是显卡驱动有点不正常，没有加速的效果，显示只有31M显存。

CPU是E3 1505，对应的内置显卡是P530，不知道是否能告知下P530如何驱动，多谢。

**Comment by darkhandz** [comment]
这个就没研究哦，你可以试试把config.plist里的0x191b0000 改成 0x19268086

**Comment by zhuzhe1983** [comment]
可以了，多谢，多谢，m5510基本上按照你的这个教程就可以完美了。

**Comment by darkhandz** [comment]
离完美还差很远呢，不过日常普通功能算是正常吧，让我们一起期待syscl大神的9350项目 :)

**Comment by soulomoon** [comment]
@zhuzhe1983 你好请问可以不可以分享一下你的CLOVER呢 我也是5510 ，安装Sierra，按照教程也安装不上去，之前在安装EI cap在tony86倒是找到了一个clover来安装成功，但是打DSTS补丁太麻烦又暂时没有网络所以继续选择安装Sierra
